language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install: pip install -r requirements.txt
deploy:
  provider: pypi
  user: hydreliox
  password:
    secure: u0TLCyJA5BK5eFqBJaZoxgSW0ESVGrOPXo99QGeEu0xlSOl5vjN70aexBrFms8zF1RbngiZl3oym5R6nYWl7CHTzltGLPbpbpv0XwjZlhxeyMGVQXzcdf12EgzBuPA2Kll5VIy6Gqb1Xo2dDkNUAmoXO2+RU1Q+EG/9bUplFLvTF/Pmx8ZAUODsXdR2HRIXSdBzjyWdyfRZr3vjVOFHDLXtVDtgngtkTJf6HL9IAH8rV4S2vnGrbsXoHJY/+TfU4Xrg2ETClt38xm0lPy0PGDakMhfBOfRmAs/1QhwoAKuR6WfInIL+ddUpeuWdYFC2/mDW5qvpVKr02BLxg53mcH3xcwO98oWh+xVNBrVK/PEtk8Hv2iWOpNgzRykNXcI3975k5kM/lmeCeh9WJVkp1y7sW+7zQtXhrwL1LNDHJL6TjL0z8kGcodBPFGpR+8y2+k/jnakjKBS0jTZgA+2EqpYWb6aaKtX+F0Bd5lbMEGvmlPrg0BCDdwZs30LVL9bhmiER1xEos0rmLOs/tOqV+K036BIgDotbQ2hG6vbjEe2YqbcGSthXGbn0xDNdW2+Gbhp+5ALvmFxhTcl/srsYQm1BUR703yx11fP4J1kTx/oy2Mc2hB0lb7pXayZIoPsxl8WbirdBAFeCHiAwTa1izN2aQiU1D6KS5gr3uuevouYo=
  on:
    tags: true
    branch: master
    python: '3.5'
script:
  - python pyEdfEjp/__init__.py